//
//  HookHTTPServer.swift
//  AFK-Agent
//
//  Native HTTP server on localhost for receiving Claude Code hook events.
//  Claude Code sends POST requests to /hooks/* endpoints when configured
//  with HTTP hook type. This replaces the shell script + Unix socket approach.
//
//  Follows the NWListener pattern from OTLPReceiver.swift.
//

import Foundation
import Network
import OSLog

// MARK: - Hook Types

struct HookEvent: @unchecked Sendable {
    let type: String  // "session_start", "session_end", "stop", "notification", "user_prompt_submit"
    let sessionId: String?
    let payload: [String: Any]  // raw JSON — values are JSON-safe Sendable types
}

struct HookPermissionRequest: Sendable {
    let sessionId: String
    let toolName: String
    let toolInput: [String: String]
    let toolUseId: String
    let cwd: String
    let nonce: String  // generated by server for tracking
}

struct HookPermissionResponse: Sendable {
    let behavior: String  // "allow" or "deny"
    let updatedInput: [String: String]?
}

struct HookToolResult: Sendable {
    let sessionId: String
    let toolName: String
    let toolInput: [String: String]
    let toolResponse: String
    let toolUseId: String
    let cwd: String
}

// MARK: - HookHTTPServer

actor HookHTTPServer {
    private var listener: NWListener?
    private let port: UInt16
    private let queue = DispatchQueue(label: "hook-http-server", qos: .utility)
    /// Maximum allowed HTTP request size (headers + body).
    private let maxRequestSize = 2_097_152  // 2 MB

    /// Pending permission-request continuations keyed by nonce.
    private var pendingPermissions: [String: CheckedContinuation<HookPermissionResponse, Never>] = [:]

    /// Timeout for permission requests (seconds).
    private let permissionTimeout: TimeInterval = 120

    // MARK: - Callbacks

    var onSessionEvent: ((HookEvent) async -> Void)?
    var onPermissionRequest: ((HookPermissionRequest) async -> HookPermissionResponse)?
    var onToolResult: ((HookToolResult) async -> Void)?

    func setOnSessionEvent(_ handler: @escaping (HookEvent) async -> Void) {
        self.onSessionEvent = handler
    }

    func setOnPermissionRequest(_ handler: @escaping (HookPermissionRequest) async -> HookPermissionResponse) {
        self.onPermissionRequest = handler
    }

    func setOnToolResult(_ handler: @escaping (HookToolResult) async -> Void) {
        self.onToolResult = handler
    }

    // MARK: - Init

    init(port: UInt16 = 19280) {
        self.port = port
    }

    // MARK: - Lifecycle

    func start() throws {
        let params = NWParameters.tcp
        params.requiredLocalEndpoint = .hostPort(host: .ipv4(.loopback), port: NWEndpoint.Port(rawValue: port)!)

        let listener = try NWListener(using: params)
        self.listener = listener

        let portNumber = port
        listener.stateUpdateHandler = { state in
            switch state {
            case .ready:
                AppLogger.hook.info("Hook HTTP server listening on 127.0.0.1:\(portNumber)")
            case .failed(let error):
                AppLogger.hook.error("Hook HTTP server failed: \(error.localizedDescription)")
            case .cancelled:
                AppLogger.hook.info("Hook HTTP server cancelled")
            default:
                break
            }
        }

        listener.newConnectionHandler = { [weak self] connection in
            self?.handleConnection(connection)
        }

        listener.start(queue: queue)

        // Write port file so hook installers can discover us
        writePortFile(portNumber)
    }

    func stop() {
        listener?.cancel()
        listener = nil

        // Cancel all pending permission continuations
        for (nonce, continuation) in pendingPermissions {
            AppLogger.hook.warning("Cancelling pending permission \(nonce.prefix(8)) on shutdown")
            continuation.resume(returning: HookPermissionResponse(behavior: "deny", updatedInput: nil))
        }
        pendingPermissions.removeAll()

        deletePortFile()
        AppLogger.hook.info("Hook HTTP server stopped")
    }

    /// Resume a pending permission request (called when iOS responds).
    func resolvePermission(nonce: String, response: HookPermissionResponse) {
        guard let continuation = pendingPermissions.removeValue(forKey: nonce) else {
            AppLogger.hook.warning("No pending permission for nonce \(nonce.prefix(8))")
            return
        }
        continuation.resume(returning: response)
    }

    // MARK: - Port File

    private nonisolated func writePortFile(_ port: UInt16) {
        let dir = BuildEnvironment.configDirectoryPath + "/run"
        let path = dir + "/hook-server.port"
        let fm = FileManager.default
        try? fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
        try? "\(port)".write(toFile: path, atomically: true, encoding: .utf8)
        AppLogger.hook.info("Wrote port file: \(path)")
    }

    private nonisolated func deletePortFile() {
        let path = BuildEnvironment.configDirectoryPath + "/run/hook-server.port"
        try? FileManager.default.removeItem(atPath: path)
    }

    // MARK: - Connection Handling

    /// Handle an incoming TCP connection. Runs on the dispatch queue (nonisolated context).
    private nonisolated func handleConnection(_ connection: NWConnection) {
        connection.start(queue: DispatchQueue(label: "hook-conn", qos: .utility))

        readHTTPRequest(connection: connection, accumulated: Data()) { [weak self] requestData in
            guard let self, let requestData, !requestData.isEmpty else {
                connection.cancel()
                return
            }

            guard let headerEnd = Self.findHeaderEnd(in: requestData) else {
                Self.sendResponse(connection: connection, status: "400 Bad Request", body: "{}")
                return
            }

            let headerData = requestData[..<headerEnd]
            let headerString = String(data: headerData, encoding: .utf8) ?? ""
            let lines = headerString.components(separatedBy: "\r\n")

            let requestLine = lines.first ?? ""
            let parts = requestLine.split(separator: " ", maxSplits: 2)
            let method = parts.first.map(String.init) ?? ""
            let path = parts.count > 1 ? String(parts[1]) : ""

            guard method == "POST" else {
                Self.sendResponse(connection: connection, status: "405 Method Not Allowed", body: "{}")
                return
            }

            var contentLength = 0
            for line in lines {
                let lower = line.lowercased()
                if lower.hasPrefix("content-length:") {
                    let value = line.dropFirst("content-length:".count).trimmingCharacters(in: .whitespaces)
                    contentLength = Int(value) ?? 0
                    break
                }
            }

            if contentLength > self.maxRequestSize {
                Self.sendResponse(connection: connection, status: "413 Payload Too Large", body: "{}")
                return
            }

            let bodyStart = headerEnd + 4  // skip \r\n\r\n
            let currentBody = requestData[bodyStart...]

            if currentBody.count >= contentLength {
                let body = Data(currentBody.prefix(contentLength))
                self.routeRequest(connection: connection, path: path, body: body)
            } else {
                let remaining = contentLength - currentBody.count
                self.readBody(connection: connection, accumulated: Data(currentBody), remaining: remaining, path: path)
            }
        }
    }

    private nonisolated func readHTTPRequest(connection: NWConnection, accumulated: Data, completion: @escaping @Sendable (Data?) -> Void) {
        connection.receive(minimumIncompleteLength: 1, maximumLength: 65536) { data, _, isComplete, error in
            if let error {
                AppLogger.hook.debug("Hook read error: \(error.localizedDescription)")
                completion(nil)
                return
            }

            var buffer = accumulated
            if let data {
                buffer.append(data)
            }

            if buffer.count > self.maxRequestSize {
                AppLogger.hook.warning("Hook request exceeded \(self.maxRequestSize) bytes, dropping")
                completion(nil)
                return
            }

            if Self.findHeaderEnd(in: buffer) != nil {
                completion(buffer)
            } else if isComplete {
                completion(buffer.isEmpty ? nil : buffer)
            } else {
                self.readHTTPRequest(connection: connection, accumulated: buffer, completion: completion)
            }
        }
    }

    private nonisolated func readBody(connection: NWConnection, accumulated: Data, remaining: Int, path: String) {
        connection.receive(minimumIncompleteLength: 1, maximumLength: min(remaining, 65536)) { [weak self] data, _, isComplete, error in
            guard let self else { return }

            if error != nil || (isComplete && data == nil) {
                Self.sendResponse(connection: connection, status: "400 Bad Request", body: "{}")
                return
            }

            var buffer = accumulated
            if let data {
                buffer.append(data)
            }

            let left = remaining - (data?.count ?? 0)
            if left <= 0 {
                self.routeRequest(connection: connection, path: path, body: buffer)
            } else {
                self.readBody(connection: connection, accumulated: buffer, remaining: left, path: path)
            }
        }
    }

    // MARK: - HTTP Helpers

    private nonisolated static func findHeaderEnd(in data: Data) -> Int? {
        let separator: [UInt8] = [0x0D, 0x0A, 0x0D, 0x0A]  // \r\n\r\n
        let bytes = [UInt8](data)
        guard bytes.count >= 4 else { return nil }
        for i in 0...(bytes.count - 4) {
            if bytes[i] == separator[0] && bytes[i+1] == separator[1]
                && bytes[i+2] == separator[2] && bytes[i+3] == separator[3] {
                return i
            }
        }
        return nil
    }

    private nonisolated static func sendResponse(connection: NWConnection, status: String, body: String) {
        let response = "HTTP/1.1 \(status)\r\nContent-Type: application/json\r\nContent-Length: \(body.utf8.count)\r\nConnection: close\r\n\r\n\(body)"
        connection.send(content: response.data(using: .utf8), contentContext: .finalMessage, isComplete: true, completion: .contentProcessed { _ in
            connection.cancel()
        })
    }

    // MARK: - Route Dispatch

    private nonisolated func routeRequest(connection: NWConnection, path: String, body: Data) {
        let json = (try? JSONSerialization.jsonObject(with: body)) as? [String: Any] ?? [:]

        Task { [weak self] in
            guard let self else {
                Self.sendResponse(connection: connection, status: "500 Internal Server Error", body: "{}")
                return
            }

            switch path {
            case "/hooks/session-start":
                await self.handleFireAndForget(type: "session_start", json: json)
                Self.sendResponse(connection: connection, status: "200 OK", body: "{}")

            case "/hooks/session-end":
                await self.handleFireAndForget(type: "session_end", json: json)
                Self.sendResponse(connection: connection, status: "200 OK", body: "{}")

            case "/hooks/user-prompt-submit":
                await self.handleFireAndForget(type: "user_prompt_submit", json: json)
                Self.sendResponse(connection: connection, status: "200 OK", body: "{}")

            case "/hooks/stop":
                await self.handleFireAndForget(type: "stop", json: json)
                Self.sendResponse(connection: connection, status: "200 OK", body: "{}")

            case "/hooks/notification":
                await self.handleFireAndForget(type: "notification", json: json)
                Self.sendResponse(connection: connection, status: "200 OK", body: "{}")

            case "/hooks/pre-tool-use":
                let responseBody = await self.handlePreToolUse(json: json)
                Self.sendResponse(connection: connection, status: "200 OK", body: responseBody)

            case "/hooks/post-tool-use":
                // Return immediately, process in background
                Self.sendResponse(connection: connection, status: "200 OK", body: "{}")
                await self.handlePostToolUse(json: json)

            case "/hooks/permission-request":
                let responseBody = await self.handlePermissionRequest(json: json)
                Self.sendResponse(connection: connection, status: "200 OK", body: responseBody)

            default:
                Self.sendResponse(connection: connection, status: "404 Not Found", body: "{}")
            }
        }
    }

    // MARK: - Route Handlers

    private func handleFireAndForget(type: String, json: [String: Any]) async {
        let sessionId = json["session_id"] as? String
        let event = HookEvent(type: type, sessionId: sessionId, payload: json)

        AppLogger.hook.debug("Hook event: \(type) session=\(sessionId?.prefix(8) ?? "nil")")

        if let handler = onSessionEvent {
            await handler(event)
        }
    }

    private func handlePreToolUse(json: [String: Any]) async -> String {
        let sessionId = json["session_id"] as? String ?? ""
        let toolName = json["tool_name"] as? String ?? ""
        let toolUseId = json["tool_use_id"] as? String ?? ""
        let cwd = json["cwd"] as? String ?? ""
        let toolInput = Self.extractStringDict(json["tool_input"])
        let nonce = UUID().uuidString.replacingOccurrences(of: "-", with: "").prefix(8).uppercased()

        let request = HookPermissionRequest(
            sessionId: sessionId,
            toolName: toolName,
            toolInput: toolInput,
            toolUseId: toolUseId,
            cwd: cwd,
            nonce: String(nonce)
        )

        AppLogger.hook.info("PreToolUse: \(toolName) session=\(sessionId.prefix(8)) nonce=\(nonce)")

        guard let handler = onPermissionRequest else {
            return Self.preToolUseResponse(decision: "approve")
        }

        let response = await handler(request)
        let decision = response.behavior == "allow" ? "approve" : "deny"
        return Self.preToolUseResponse(decision: decision)
    }

    private func handlePostToolUse(json: [String: Any]) async {
        let sessionId = json["session_id"] as? String ?? ""
        let toolName = json["tool_name"] as? String ?? ""
        let toolUseId = json["tool_use_id"] as? String ?? ""
        let cwd = json["cwd"] as? String ?? ""
        let toolInput = Self.extractStringDict(json["tool_input"])
        let toolResponse = json["tool_response"] as? String ?? ""

        let result = HookToolResult(
            sessionId: sessionId,
            toolName: toolName,
            toolInput: toolInput,
            toolResponse: toolResponse,
            toolUseId: toolUseId,
            cwd: cwd
        )

        AppLogger.hook.debug("PostToolUse: \(toolName) session=\(sessionId.prefix(8))")

        if let handler = onToolResult {
            await handler(result)
        }
    }

    private func handlePermissionRequest(json: [String: Any]) async -> String {
        let sessionId = json["session_id"] as? String ?? ""
        let toolName = json["tool_name"] as? String ?? ""
        let toolUseId = json["tool_use_id"] as? String ?? ""
        let cwd = json["cwd"] as? String ?? ""
        let toolInput = Self.extractStringDict(json["tool_input"])
        let nonce = UUID().uuidString.replacingOccurrences(of: "-", with: "").prefix(8).uppercased()

        AppLogger.hook.info("PermissionRequest: \(toolName) session=\(sessionId.prefix(8)) nonce=\(nonce)")

        // Hold the connection open via continuation until iOS responds or timeout
        let response: HookPermissionResponse = await withCheckedContinuation { continuation in
            // Must store inside actor isolation — we're already in actor context here
            self.pendingPermissions[String(nonce)] = continuation

            // Fire the callback to forward to iOS (non-blocking from continuation's perspective)
            Task { [weak self] in
                guard let self else { return }
                let request = HookPermissionRequest(
                    sessionId: sessionId,
                    toolName: toolName,
                    toolInput: toolInput,
                    toolUseId: toolUseId,
                    cwd: cwd,
                    nonce: String(nonce)
                )
                if let handler = await self.onPermissionRequest {
                    // We don't use the return value here — iOS will call resolvePermission
                    _ = await handler(request)
                }
            }

            // Timeout: auto-deny if no response
            Task { [weak self] in
                guard let self else { return }
                try? await Task.sleep(for: .seconds(self.permissionTimeout))
                await self.timeoutPermission(nonce: String(nonce))
            }
        }

        let decision: String
        if response.behavior == "allow" {
            if let updated = response.updatedInput {
                decision = Self.jsonString(["behavior": "allow", "updatedInput": updated])
            } else {
                decision = Self.jsonString(["behavior": "allow"])
            }
        } else {
            decision = Self.jsonString(["behavior": "deny"])
        }

        return """
        {"hookSpecificOutput":{"hookEventName":"PermissionRequest","decision":\(decision)}}
        """
    }

    private func timeoutPermission(nonce: String) {
        guard let continuation = pendingPermissions.removeValue(forKey: nonce) else { return }
        AppLogger.hook.warning("Permission request timed out: nonce=\(nonce.prefix(8))")
        continuation.resume(returning: HookPermissionResponse(behavior: "deny", updatedInput: nil))
    }

    // MARK: - Helpers

    private static func extractStringDict(_ value: Any?) -> [String: String] {
        guard let dict = value as? [String: Any] else { return [:] }
        var result: [String: String] = [:]
        for (key, val) in dict {
            if let str = val as? String {
                result[key] = str
            } else if let num = val as? NSNumber {
                result[key] = num.stringValue
            } else if let bool = val as? Bool {
                result[key] = bool ? "true" : "false"
            } else if JSONSerialization.isValidJSONObject(val),
                      let data = try? JSONSerialization.data(withJSONObject: val),
                      let str = String(data: data, encoding: .utf8) {
                result[key] = str
            } else {
                result[key] = String(describing: val)
            }
        }
        return result
    }

    private static func preToolUseResponse(decision: String) -> String {
        return """
        {"hookSpecificOutput":{"hookEventName":"PreToolUse","decision":"\(decision)"}}
        """
    }

    private static func jsonString(_ value: Any) -> String {
        guard let data = try? JSONSerialization.data(withJSONObject: value),
              let str = String(data: data, encoding: .utf8) else {
            return "{}"
        }
        return str
    }
}
